export const ROUTES = {
	invite: "https://forms.gle/3gdV6YFEyYDmVNdn7",
	app: "https://alpha.infinidream.ai",
	createAccount: "https://alpha.infinidream.ai/account",
	discord: "https://discord.gg/x42WkXwwWG",
	bluesky: "https://bsky.app/profile/infinidream.ai",
	github: "https://github.com/e-dream-ai",
	facebook: "https://www.facebook.com/groups/infinidreamai",
	instagram: "https://www.instagram.com/infinidream_ai",
	x: "https://x.com/infinidream_ai",
	issues: "https://github.com/e-dream-ai/client/issues/new",
	api: "https://github.com/e-dream-ai/python-api",
	creators: "https://forms.gle/JsZb4TRdw3jq65Bc8",
	// Team member routes
	scottDraves: "https://draves.ai",
	electricSheep: "https://scottdraves.com/sheep.html",
	maxCarlson: "https://www.linkedin.com/in/max-carlson-8959531/",
	guillaumeLouel: "https://github.com/glouel",
	aerial: "https://aerialscreensaver.github.io/",
	miklosNagy: "https://magixworld.com/",
	deforum: "https://github.com/XmYx",
	patreon: "https://www.patreon.com/c/Infinidream",
};
